name: anlık dinleme için güncelleyici workflow

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: depoyu klonla
        uses: actions/checkout@v3

      - name: parça verisini çek
        run: |
          curl -X "GET" "https://api.spotify.com/v1/me/player/currently-playing" \
            -H "Authorization: Bearer ${{ secrets.SPOTIFY_ACCESS_TOKEN }}" \
            -H "Content-Type: application/json" | jq '.' > now-playing.json

      - name: değişiklikleri commit et
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add now-playing.json
          git commit -m "guncel-parca-verisi" || exit 0
          git push
